package com.example.wzb.entity;

import java.io.Serializable;

public class TPayBill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.updateTime
     *
     * @mbg.generated
     */
    private Long updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.createTime
     *
     * @mbg.generated
     */
    private Long createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.ssoId
     *
     * @mbg.generated
     */
    private Long ssoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.unionPaySn
     *
     * @mbg.generated
     */
    private String unionpaysn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.money
     *
     * @mbg.generated
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.businessType
     *
     * @mbg.generated
     */
    private Byte businesstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.businessKey
     *
     * @mbg.generated
     */
    private Long businesskey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.payChannel
     *
     * @mbg.generated
     */
    private Byte paychannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.digest
     *
     * @mbg.generated
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.originalPayBillId
     *
     * @mbg.generated
     */
    private Long originalpaybillid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.originalUnionPaySn
     *
     * @mbg.generated
     */
    private String originalunionpaysn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_bill.lastPayTime
     *
     * @mbg.generated
     */
    private Long lastpaytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_bill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.id
     *
     * @return the value of t_pay_bill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.id
     *
     * @param id the value for t_pay_bill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.updateTime
     *
     * @return the value of t_pay_bill.updateTime
     *
     * @mbg.generated
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.updateTime
     *
     * @param updatetime the value for t_pay_bill.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.createTime
     *
     * @return the value of t_pay_bill.createTime
     *
     * @mbg.generated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.createTime
     *
     * @param createtime the value for t_pay_bill.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.ssoId
     *
     * @return the value of t_pay_bill.ssoId
     *
     * @mbg.generated
     */
    public Long getSsoid() {
        return ssoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.ssoId
     *
     * @param ssoid the value for t_pay_bill.ssoId
     *
     * @mbg.generated
     */
    public void setSsoid(Long ssoid) {
        this.ssoid = ssoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.nickName
     *
     * @return the value of t_pay_bill.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.nickName
     *
     * @param nickname the value for t_pay_bill.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.unionPaySn
     *
     * @return the value of t_pay_bill.unionPaySn
     *
     * @mbg.generated
     */
    public String getUnionpaysn() {
        return unionpaysn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.unionPaySn
     *
     * @param unionpaysn the value for t_pay_bill.unionPaySn
     *
     * @mbg.generated
     */
    public void setUnionpaysn(String unionpaysn) {
        this.unionpaysn = unionpaysn == null ? null : unionpaysn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.money
     *
     * @return the value of t_pay_bill.money
     *
     * @mbg.generated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.money
     *
     * @param money the value for t_pay_bill.money
     *
     * @mbg.generated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.businessType
     *
     * @return the value of t_pay_bill.businessType
     *
     * @mbg.generated
     */
    public Byte getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.businessType
     *
     * @param businesstype the value for t_pay_bill.businessType
     *
     * @mbg.generated
     */
    public void setBusinesstype(Byte businesstype) {
        this.businesstype = businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.businessKey
     *
     * @return the value of t_pay_bill.businessKey
     *
     * @mbg.generated
     */
    public Long getBusinesskey() {
        return businesskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.businessKey
     *
     * @param businesskey the value for t_pay_bill.businessKey
     *
     * @mbg.generated
     */
    public void setBusinesskey(Long businesskey) {
        this.businesskey = businesskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.payChannel
     *
     * @return the value of t_pay_bill.payChannel
     *
     * @mbg.generated
     */
    public Byte getPaychannel() {
        return paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.payChannel
     *
     * @param paychannel the value for t_pay_bill.payChannel
     *
     * @mbg.generated
     */
    public void setPaychannel(Byte paychannel) {
        this.paychannel = paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.note
     *
     * @return the value of t_pay_bill.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.note
     *
     * @param note the value for t_pay_bill.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.digest
     *
     * @return the value of t_pay_bill.digest
     *
     * @mbg.generated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.digest
     *
     * @param digest the value for t_pay_bill.digest
     *
     * @mbg.generated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.state
     *
     * @return the value of t_pay_bill.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.state
     *
     * @param state the value for t_pay_bill.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.originalPayBillId
     *
     * @return the value of t_pay_bill.originalPayBillId
     *
     * @mbg.generated
     */
    public Long getOriginalpaybillid() {
        return originalpaybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.originalPayBillId
     *
     * @param originalpaybillid the value for t_pay_bill.originalPayBillId
     *
     * @mbg.generated
     */
    public void setOriginalpaybillid(Long originalpaybillid) {
        this.originalpaybillid = originalpaybillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.originalUnionPaySn
     *
     * @return the value of t_pay_bill.originalUnionPaySn
     *
     * @mbg.generated
     */
    public String getOriginalunionpaysn() {
        return originalunionpaysn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.originalUnionPaySn
     *
     * @param originalunionpaysn the value for t_pay_bill.originalUnionPaySn
     *
     * @mbg.generated
     */
    public void setOriginalunionpaysn(String originalunionpaysn) {
        this.originalunionpaysn = originalunionpaysn == null ? null : originalunionpaysn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_bill.lastPayTime
     *
     * @return the value of t_pay_bill.lastPayTime
     *
     * @mbg.generated
     */
    public Long getLastpaytime() {
        return lastpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_bill.lastPayTime
     *
     * @param lastpaytime the value for t_pay_bill.lastPayTime
     *
     * @mbg.generated
     */
    public void setLastpaytime(Long lastpaytime) {
        this.lastpaytime = lastpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_bill
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", createtime=").append(createtime);
        sb.append(", ssoid=").append(ssoid);
        sb.append(", nickname=").append(nickname);
        sb.append(", unionpaysn=").append(unionpaysn);
        sb.append(", money=").append(money);
        sb.append(", businesstype=").append(businesstype);
        sb.append(", businesskey=").append(businesskey);
        sb.append(", paychannel=").append(paychannel);
        sb.append(", note=").append(note);
        sb.append(", digest=").append(digest);
        sb.append(", state=").append(state);
        sb.append(", originalpaybillid=").append(originalpaybillid);
        sb.append(", originalunionpaysn=").append(originalunionpaysn);
        sb.append(", lastpaytime=").append(lastpaytime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}